package com.moakiee.ae2lt.logic.tianshu;

public enum TianshuMultiblockScanIssue {
    MISSING_CASING,
    MISSING_COOLING,
    MISSING_GLASS,
    MISSING_PORT,
    MULTIPLE_PORTS,
    INVALID_CONTROLLER,
    MISSING_MAIN_CORE,
    MAIN_CORE_OUTSIDE_CENTER,
    INVALID_PERIPHERAL_UNIT,
    MISSING_PARALLEL_UNIT,
    TOO_MANY_AMPLIFIER_UNITS,
    AMPLIFIER_UNIT_NOT_SUPPORTED,
    CHUNKS_UNLOADED
}
