package com.moakiee.ae2lt.logic.craft;

public enum MatrixMultiblockScanIssue {
    UNEXPECTED_COMPONENT,
    MISSING_PORT,
    MULTIPLE_PORTS,
    MISSING_MAIN_CORE,
    MISSING_PATTERN_STORAGE,
    MAIN_CORE_OUTSIDE_CENTER,
    AMPLIFIER_LIMIT_EXCEEDED,
    MISSING_DISPATCH_UNIT,
    AMPLIFIER_NOT_SUPPORTED,
    MULTIDIMENSIONAL_UNIT_NOT_SUPPORTED,
    CHUNKS_UNLOADED
}
